#端口
server:
  port: 8090

#jdbc 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/four?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456


#Mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml