#端口
server:
  port: 8090

#jdbc 数据库
spring:
  datasource:
    url: jdbc:mysql://39.106.40.119:3306/four?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  activiti:
    database-schema: true
    history-level: full
  http:
    encoding:
      force: true

#Mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#打印sql语句记录
logging:
  level:
    com.yh.dao: debug
  path: F:\home\temp_djp
  pattern:
    console: '%d{YYYY-MM-DD HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'


banner:
  charset: UTF-8