#端口
server:
  port: 8090

#jdbc 数据库
spring:
  datasource:
    url: jdbc:mysql://39.106.40.119:3306/four?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  activiti:
    database-schema: true
    history-level: full

#Mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#打印sql语句记录
logging:
  level:
    com.yh.dao: debug

banner:
  charset: UTF-8